global:
  name: Restaurant Technology Landscape
  short_name: Restaurant Technology
  repo: open-restaurant/restaurant-technology-landscape
  website: 'http://open-restaurant.io/'
  short_domain: open-restaurant.io
  company_url: 'http://open-restaurant.io/'
  email: info@open-restaurant.io
  self: 'https://www.crunchbase.com/organization/graphql-foundation'
  slack_channel: T08PSQ7BQ/BM7M5TKSR/Xjll8jWb2cgpO7aOCGxUtebU
  meta:
    title: Restaurant Technology Landscape
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@graphql'
    google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: Restaurant Technology Foundation Member
  flags:
    hide_license_for_categories:
      - Restaurant Technology Adopter
      - Restaurant Technology Foundation Member
twitter:
  search: open-restaurant.io
  url: 'https://open-restaurant.io'
  text: Restaurant Technology Landscape
relation:
  label: Restaurant Technology Relation
  url: open-restaurant
  values:
    - id: hosted
      label: Restaurant Technology Foundation Projects
      children:
        - id: foundationproject
          label: Restaurant Technology Foundation Projects
          prefix: Restaurant Technology
          tag: Foundation Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Restaurant Technology Foundation Project
          big_picture_color: 'rgb(24,54,114)'
    - id: company
      label: Restaurant Technology Foundation Member
      tag: Company
      big_picture_order: 3
    - id: member
      label: Restaurant Technology Foundation Member Products/Projects
      tag: Restaurant Technology Foundation Member
    - id: false
      label: Non-Restaurant Technology Foundation Member Products/Projects
      url: 'no'
membership:
  General:
    name: Restaurant Technology
    label: Member
    funding: General
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  'false':
    funding: 'No'
home:
  header: >
    <h1>Restaurant Technology Landscape</h1> The Restaurant Technology Landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads: []
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Restaurant Technology Landscape Landscape
    fullscreen_header: See the interactive landscape at open-restaurant.io
    elements:
      - type: VerticalCategory
        category: Guest Experience
        cols: 6
        width: 450
        height: 620
        top: 0
        left: 0
        color: 'rgb(4,81,49)'
        fit_width: true
      - type: VerticalCategory
        category: Operations
        cols: 6
        width: 450
        height: 620
        top: 0
        left: 470
        color: 'rgb(7,136,62)'
        fit_width: true
      - type: HorizontalCategory
        category: Point Of Sale
        rows: 3
        width: 920
        height: 160
        top: 640
        left: 0
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: VerticalCategory
        category: Restaurant Technology Adopter
        cols: 4
        width: 450
        height: 800
        top: 0
        left: 940
        color: 'rgb(126,115,14)'
        fit_width: false
      - type: LandscapeInfo
        width: 310
        height: 200
        top: 820
        left: 0
        children:
          - type: text
            text: >
              This landscape is intended as a map to explore the Restaurant Technology community, and also shows the member organizations of the Restaurant
              Technology Foundation.
            top: 55
            left: 140
            right: 10
            font_size: 10
          - type: image
            image: qr.svg
            top: 55
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: open-restaurant.io
            top: 140
            left: 5
            font_size: 21
          - type: image
            image: left-logo.svg
            width: 110
            right: 190
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 109
            right: 10
            top: 10
            title: Restaurant Technology Foundation Logo
      - type: HorizontalCategory
        category: Restaurant Technology Foundation Member
        rows: 4
        width: 1060
        height: 200
        top: 820
        left: 330
        color: 'rgb(103,66,18)'
        fit_width: true
test:
  header: Restaurant Technology Landscape
  section: Restaurant Technology Foundation Member
  logo: nandos-adopter.svg
