steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret='secret-for-pulumi' --format='get(payload.data)' | tr '_-' '/+' | base64 -d > pulumi-data.txt" ]
- name: 'gcr.io/cloud-builders/yarn:current'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - 'export PULUMI_ACCESS_TOKEN=`cat pulumi-data.txt` && chmod +x ./infrastructure/gcp/site/scripts/*.sh && cd ./infrastructure/gcp/site && ./scripts/pulumi.sh'
  env:
  - 'BUILD_TYPE=$_BUILD_TYPE'
  - 'BUILD_STACK=$_BUILD_STACK'
