steps:
- name: 'gcr.io/cloud-builders/npm:current'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - 'chmod +x ./website/scripts/*.sh && cd ./website && ./scripts/google.sh'
  env:
  - 'BUCKET_NAME=$_BUCKET_NAME'
