steps:
- name: 'gcr.io/cloud-builders/npm:current'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - 'chmod +x ./website/scripts/*.sh && cd ./website && ./scripts/google.sh'
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - 'gsutil rsync -r -d website/dist gs://$$BUCKET_NAME'
  env:
    - 'BUCKET_NAME=$_BUCKET_NAME'